# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: mt's blog
tagline: mt's blog
description: random ideas
url: https://matm.xyz
baseurl: /

version: '2.0'
github:
  repo: https://github.com/manueltarouca

author:
  name: "Manuel Tarouca Martins"

paginate: 5

theme: jekyll-theme-minimal